import {TypePlacesInfo} from '../types/types.ts';

export const offers: TypePlacesInfo[] = [
  {
    id: 1,
    isPremium: true,
    href: '#',
    image: 'img/apartment-01.jpg',
    price: 120,
    rating: 4,
    name: 'Beautiful & luxurious apartment at great location',
    type: 'Apartment',
  },
  {
    id:2,
    href: '#',
    isBookmarked: true,
    image: 'img/room.jpg',
    price: 80,
    rating: 4,
    name: 'Wood and stone place',
    type: 'Room',
  },
  {
    id:3,
    href: '#',
    image: 'img/apartment-02.jpg',
    price: 132,
    rating: 4,
    name: 'Canal View Prinsengracht',
    type: 'Apartment',
  },
  {
    id:4,
    isPremium: true,
    href: '#',
    image: 'img/apartment-03.jpg',
    price: 180,
    rating: 4,
    name: 'Nice, cozy, warm big bed apartment',
    type: 'Apartment',
  },
  {
    id:5,
    href: '#',
    image: 'img/room.jpg',
    price: 80,
    isBookmarked: true,
    rating: 4,
    name: 'Wood and stone place',
    type: 'Room',
  },
];
